<br />
<font size='1'><table class='xdebug-error xe-uncaught-exception' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Fatal error: Uncaught Error: Call to undefined function add_action() in /Users/Davide/Sites/www.digitalwave.dev.cc/wp-content/themes/Divi/includes/builder/feature/custom-defaults/History.php on line <i>30</i></th></tr>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Error: Call to undefined function add_action() in /Users/Davide/Sites/www.digitalwave.dev.cc/wp-content/themes/Divi/includes/builder/feature/custom-defaults/History.php on line <i>30</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0018</td><td bgcolor='#eeeeec' align='right'>525448</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='/Users/Davide/Sites/www.digitalwave.dev.cc/wp-content/themes/Divi/includes/builder/feature/custom-defaults/History.php' bgcolor='#eeeeec'>.../History.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.0018</td><td bgcolor='#eeeeec' align='right'>525448</td><td bgcolor='#eeeeec'>ET_Builder_Custom_Defaults_History::instance(  )</td><td title='/Users/Davide/Sites/www.digitalwave.dev.cc/wp-content/themes/Divi/includes/builder/feature/custom-defaults/History.php' bgcolor='#eeeeec'>.../History.php<b>:</b>239</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>0.0018</td><td bgcolor='#eeeeec' align='right'>525488</td><td bgcolor='#eeeeec'>ET_Builder_Custom_Defaults_History->__construct(  )</td><td title='/Users/Davide/Sites/www.digitalwave.dev.cc/wp-content/themes/Divi/includes/builder/feature/custom-defaults/History.php' bgcolor='#eeeeec'>.../History.php<b>:</b>23</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>4</td><td bgcolor='#eeeeec' align='center'>0.0018</td><td bgcolor='#eeeeec' align='right'>525488</td><td bgcolor='#eeeeec'>ET_Builder_Custom_Defaults_History->_register_ajax_callbacks(  )</td><td title='/Users/Davide/Sites/www.digitalwave.dev.cc/wp-content/themes/Divi/includes/builder/feature/custom-defaults/History.php' bgcolor='#eeeeec'>.../History.php<b>:</b>10</td></tr>
</table></font>
