<br />
<font size='1'><table class='xdebug-error xe-uncaught-exception' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Fatal error: Uncaught Error: Call to undefined function et_get_option() in /Users/Davide/Sites/www.digitalwave.dev.cc/wp-content/themes/Divi/includes/builder/feature/custom-defaults/Settings.php on line <i>62</i></th></tr>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Error: Call to undefined function et_get_option() in /Users/Davide/Sites/www.digitalwave.dev.cc/wp-content/themes/Divi/includes/builder/feature/custom-defaults/Settings.php on line <i>62</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0026</td><td bgcolor='#eeeeec' align='right'>519584</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='/Users/Davide/Sites/www.digitalwave.dev.cc/wp-content/themes/Divi/includes/builder/feature/custom-defaults/Settings.php' bgcolor='#eeeeec'>.../Settings.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.0027</td><td bgcolor='#eeeeec' align='right'>519584</td><td bgcolor='#eeeeec'>ET_Builder_Custom_Defaults_Settings::instance(  )</td><td title='/Users/Davide/Sites/www.digitalwave.dev.cc/wp-content/themes/Divi/includes/builder/feature/custom-defaults/Settings.php' bgcolor='#eeeeec'>.../Settings.php<b>:</b>320</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>0.0027</td><td bgcolor='#eeeeec' align='right'>519640</td><td bgcolor='#eeeeec'>ET_Builder_Custom_Defaults_Settings->__construct(  )</td><td title='/Users/Davide/Sites/www.digitalwave.dev.cc/wp-content/themes/Divi/includes/builder/feature/custom-defaults/Settings.php' bgcolor='#eeeeec'>.../Settings.php<b>:</b>82</td></tr>
</table></font>
